// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elastacloud.AzureManagement.Fluent")]
[assembly: AssemblyDescriptionAttribute("Library used for management of Windows Azure services, SQL, storage, networking, WASD, WAMS and VM's")]
[assembly: AssemblyCompanyAttribute("Elastacloud Limited")]
[assembly: AssemblyProductAttribute("Azure Fluent Management")]
[assembly: AssemblyCopyrightAttribute("Copyright Elastacloud Limited © 2015")]
[assembly: ComVisibleAttribute(false)]
[assembly: GuidAttribute("909b2b8c-10bf-4f0d-a94e-208ef3bdca52")]
[assembly: InternalsVisibleToAttribute("DynamicProxyGenAssembly2")]
[assembly: InternalsVisibleToAttribute("Elastacloud.AzureManagement.Fluent.Tests")]
[assembly: AssemblyVersionAttribute("0.5.1.8")]
[assembly: AssemblyFileVersionAttribute("0.5.1.8")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.5.1.8";
    }
}
